services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    restart: always
    tty: true
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - nodejs

  nodejs:
    build: 
      context: nodejs
    container_name: nodejs
    hostname: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s npm start
    restart: always
    tty: true
    volumes:
      - ./nodejs:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodenet
    ports:
      - "3000:3000"
    depends_on: 
      - db

  db:
    image: mysql:8.0
    container_name: db
    hostname: db
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

networks:
  nodenet:
    driver: bridge