package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type AutoGenerated struct {
	Usdbrl struct {
		Bid string `json:"bid"`
	} `json:"USDBRL"`
}

type Cotacao struct {
	ID  int `gorm:primaryKey`
	Bid string
	gorm.Model
}

func main() {
	db, _ := obterConexao()
	db.AutoMigrate(&Cotacao{})

	http.HandleFunc("/cotacao", handler)
	http.ListenAndServe(":8080", nil)
}

func obterConexao() (db *gorm.DB, err error) {
	db, err = gorm.Open(sqlite.Open("goexpert.db"), &gorm.Config{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Erro ao obter conexão com o banco de dados: %v\n", err)
		return nil, err
	}
	return db, nil
}

func handler(w http.ResponseWriter, r *http.Request) {
	bid, err := consultarAPI()
	if err != nil {
		panic(err)
	}

	err = persistirBancoDeDados(bid)
	if err != nil {
		panic(err)
	}

	w.Write([]byte(bid))
}

func consultarAPI() (string, error) {
	ctx := context.Background()
	ctx, cancel := context.WithTimeout(ctx, 200*time.Millisecond)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, "GET", "https://economia.awesomeapi.com.br/json/last/USD-BRL", nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Erro ao montar a requisição: %v\n", err)
		return "", err
	}

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Erro ao fazer a requisição: %v\n", err)
		return "", err
	}

	defer res.Body.Close()
	resBody, err := io.ReadAll(res.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Erro ao ler resposta: %v\n", err)
		return "", err
	}

	var data AutoGenerated
	err = json.Unmarshal(resBody, &data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Erro ao desempacotar o JSON: %v\n", err)
		return "", err
	}
	return data.Usdbrl.Bid, nil
}

func persistirBancoDeDados(valor string) error {
	ctx := context.Background()
	ctx, cancel := context.WithTimeout(ctx, 10*time.Millisecond)
	defer cancel()

	db, err := obterConexao()
	if err != nil {
		return err
	}

	return db.WithContext(ctx).Create(&Cotacao{
		Bid: valor,
	}).Error
}
